<link href="<?php echo Mage::getBaseUrl('skin')?>frontend/default/hbslider/css/bjqs.css" type="text/css" media="all" rel="stylesheet" />
<link href="<?php echo Mage::getBaseUrl('skin')?>frontend/default/hbslider/css/hb.css" type="text/css" media="all" rel="stylesheet" />

<script type="text/javascript" language="javascript" src="<?php echo Mage::getBaseUrl('skin')?>frontend/default/hbslider/js/jquery-1.7.1.min.js">
</script>

<script type="text/javascript" language="javascript" src="<?php echo Mage::getBaseUrl('skin')?>frontend/default/hbslider/js/bjqs-1.3.min.js">
</script>

<script type="text/javascript" language="javascript">
		$(document).ready(function($) {

          $('#banner-fade').bjqs({
            height      : 320,
            width       : 620,
            responsive  : true
          });

        });
	</script>

<?php
	echo $this->methodblock();
?>

    